[phases.setup]
nixPkgs = ["python313"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "streamlit run FrontEnd/ventas_app_simple.py --server.port 8501 --server.address 0.0.0.0 --server.headless true"
